### PR TITLE
Changed Presence leave join callback order to better match expected event order

### PR DESCRIPTION
**Pull request by rawnsley**
There [appears to be a convention](https://github.com/phoenixframework/phoenix/issues/1639#issuecomment-208433900) that when updating the properties associated with a Presence it should _leave_ then _join_. I was slightly surprised that there isn't a less radical "property update event" of some kind, but I guess this could be added if required by a client?

Either way, it is assumed that the _leave_ and _join_ events will be processed in the order they are given in the JSON packet, but this is not the case currently in JavaPhoenixClient, which always processes _join_ first. This can lead to clients processing the _join_ and then erroneously removing the Presence when processing the _leave_.

The PR is only a band-aid solution as it doesn't actually process the events in the JSON order, but just in _leave-join_ order to fix the immediate problem. Feel free to reject in favour of something more comprehensive.

For reference, I came across the problem when connecting to Mozilla Hubs, which has this exact behaviour when updating properties like _displayName_ or _avatarId_.

### CODE REVIEW

**Comment by dsrees** [comment]
Not sure i'm willing to move these around, since the current implementation mirrors the JS library and the issue you linked is several years old. How are you processing Presence changes?

**Comment by rawnsley** [comment]
I can see it in the JS library; perhaps I'm not understanding Presence well enough then. Here is roughly how I'm trying to track player Presence in a networked game:

```
    // Track the players by ID
    private val playerMap = mutableMapOf<String, Player>()
    var presence : Presence? = null

    // Fired when the Channel has opened
    fun channelJoinedHandler(channel : Channel) {
        presence = Presence(channel)
        presence?.onJoin(::onJoinHandler)
        presence?.onLeave(::onLeaveHandler)
    }

    fun onJoinHandler(id: String, current: PresenceMap?, new: PresenceMap) {
            var player = playerMap[id]
            if (player == null) {
                player = Player.fromPresence(id, new)
                info("Player $player joined")
                playerMap[id] = player
                playerJoined(player)
            } else {
                info("PLAYER UPDATE: $id $new")
            }
    }

    fun onLeaveHandler(id: String, current: PresenceMap, new: PresenceMap) {
            val player = playerMap[id]
            if (player == null) {
                err("Unexpected player leave event $id $new")
            } else {
                info("Player $player left")
                playerMap.remove(id)
                playerLeft(player)
            }
    }
```

The map of Players mirrors the Presences, but if we process the Join before the Leave, the map will end up empty if the same Presence joins and leaves in a single diff event.

Should I be keeping account of the _metas_ instead and only removing players once they have no active meta data? Or should I not try and mirror presence this way at all?

**Comment by dsrees** [comment]
In earlier versions of phoenix, there existed a race condition between the onjoin/onleave callbacks. The way around it is to use `onSync` which gets called after all of the `onJoin`/`onLeave` logic has been completed and then looking at the state of the `Presence` after

instead of using `onJoin`/`onLeave`, instead use `onSync` combined with the `.listBy` method

```Kotlin
presence?.onSync {
   // Map the current synced PresenceState into a List<Player> 
   val players = presence.listBy() { playerPresenceMap -> Player.fromPresence(playerPresenceMap) }
}
```

**Comment by dsrees** [comment]
Closing since I don't believe this is a proper solution and the use of `onSync` should solve the issue

**Pull request closed without merging**
